//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lex4all.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("lex4all.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AA
        ///AE
        ///AH
        ///AI
        ///AO
        ///AU
        ///AX
        ///E
        ///EH
        ///EI
        ///I
        ///IH
        ///O
        ///OI
        ///U
        ///UH
        ///B
        ///CH
        ///D
        ///DH
        ///F
        ///G
        ///H
        ///J
        ///JH
        ///K
        ///L
        ///M
        ///N
        ///NG
        ///P
        ///R
        ///S
        ///SH
        ///T
        ///TH
        ///V
        ///W
        ///Z
        ///ZH.
        /// </summary>
        public static string en_US_wildcard1 {
            get {
                return ResourceManager.GetString("en_US_wildcard1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AA
        ///AE
        ///AH
        ///AI
        ///AO
        ///AU
        ///AX
        ///E
        ///EH
        ///EI
        ///I
        ///IH
        ///O
        ///OI
        ///U
        ///UH
        ///B
        ///CH
        ///D
        ///DH
        ///F
        ///G
        ///H
        ///J
        ///JH
        ///K
        ///L
        ///M
        ///N
        ///NG
        ///P
        ///R
        ///S
        ///SH
        ///T
        ///TH
        ///V
        ///W
        ///Z
        ///ZH
        ///AA AA
        ///AA AE
        ///AA AH
        ///AA AI
        ///AA AO
        ///AA AU
        ///AA AX
        ///AA E
        ///AA EH
        ///AA EI
        ///AA I
        ///AA IH
        ///AA O
        ///AA OI
        ///AA U
        ///AA UH
        ///AA B
        ///AA CH
        ///AA D
        ///AA DH
        ///AA F
        ///AA G
        ///AA H
        ///AA J
        ///AA JH
        ///AA K
        ///AA L
        ///AA M
        ///AA N
        ///AA NG
        ///AA P
        ///AA R
        ///AA S
        ///AA SH
        ///AA T
        ///AA TH
        ///AA V
        ///AA W
        ///AA Z
        ///AA ZH
        ///AE AA
        ///AE AE
        ///AE AH
        ///AE AI
        ///AE AO
        ///AE AU
        ///AE AX
        ///AE E
        ///AE EH
        ///AE EI
        ///AE I
        ///AE IH
        ///AE O
        ///AE OI
        ///AE U
        ///AE UH
        ///AE B
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string en_US_wildcard12 {
            get {
                return ResourceManager.GetString("en_US_wildcard12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AA
        ///AE
        ///AH
        ///AI
        ///AO
        ///AU
        ///AX
        ///E
        ///EH
        ///EI
        ///I
        ///IH
        ///O
        ///OI
        ///U
        ///UH
        ///B
        ///CH
        ///D
        ///DH
        ///F
        ///G
        ///H
        ///J
        ///JH
        ///K
        ///L
        ///M
        ///N
        ///NG
        ///P
        ///R
        ///S
        ///SH
        ///T
        ///TH
        ///V
        ///W
        ///Z
        ///ZH
        ///AA AA
        ///AA AE
        ///AA AH
        ///AA AI
        ///AA AO
        ///AA AU
        ///AA AX
        ///AA E
        ///AA EH
        ///AA EI
        ///AA I
        ///AA IH
        ///AA O
        ///AA OI
        ///AA U
        ///AA UH
        ///AA B
        ///AA CH
        ///AA D
        ///AA DH
        ///AA F
        ///AA G
        ///AA H
        ///AA J
        ///AA JH
        ///AA K
        ///AA L
        ///AA M
        ///AA N
        ///AA NG
        ///AA P
        ///AA R
        ///AA S
        ///AA SH
        ///AA T
        ///AA TH
        ///AA V
        ///AA W
        ///AA Z
        ///AA ZH
        ///AE AA
        ///AE AE
        ///AE AH
        ///AE AI
        ///AE AO
        ///AE AU
        ///AE AX
        ///AE E
        ///AE EH
        ///AE EI
        ///AE I
        ///AE IH
        ///AE O
        ///AE OI
        ///AE U
        ///AE UH
        ///AE B
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string en_US_wildcard123 {
            get {
                return ResourceManager.GetString("en_US_wildcard123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream sampleAudio {
            get {
                return ResourceManager.GetStream("sampleAudio", resourceCulture);
            }
        }
    }
}
