//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lex4all.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("lex4all.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A
        ///AW
        ///AX
        ///AY
        ///B
        ///D
        ///CH
        ///EH
        ///EU
        ///EY
        ///F
        ///G
        ///H
        ///IH
        ///IY
        ///JH
        ///K
        ///L
        ///M
        ///N
        ///NG
        ///OE
        ///OH
        ///OW
        ///OY
        ///P
        ///PF
        ///R
        ///S
        ///SH
        ///T
        ///TS
        ///UE
        ///UH
        ///UW
        ///UY
        ///V
        ///X
        ///Y
        ///Z
        ///ZH.
        /// </summary>
        public static string de_DE_wildcard1 {
            get {
                return ResourceManager.GetString("de_DE_wildcard1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A
        ///AW
        ///AX
        ///AY
        ///B
        ///D
        ///CH
        ///EH
        ///EU
        ///EY
        ///F
        ///G
        ///H
        ///IH
        ///IY
        ///JH
        ///K
        ///L
        ///M
        ///N
        ///NG
        ///OE
        ///OH
        ///OW
        ///OY
        ///P
        ///PF
        ///R
        ///S
        ///SH
        ///T
        ///TS
        ///UE
        ///UH
        ///UW
        ///UY
        ///V
        ///X
        ///Y
        ///Z
        ///ZH
        ///A A
        ///A AW
        ///A AX
        ///A AY
        ///A B
        ///A D
        ///A CH
        ///A EH
        ///A EU
        ///A EY
        ///A F
        ///A G
        ///A H
        ///A IH
        ///A IY
        ///A JH
        ///A K
        ///A L
        ///A M
        ///A N
        ///A NG
        ///A OE
        ///A OH
        ///A OW
        ///A OY
        ///A P
        ///A PF
        ///A R
        ///A S
        ///A SH
        ///A T
        ///A TS
        ///A UE
        ///A UH
        ///A UW
        ///A UY
        ///A V
        ///A X
        ///A Y
        ///A Z
        ///A ZH
        ///AW A
        ///AW AW
        ///AW AX
        ///AW AY
        ///AW B
        ///AW D
        ///AW CH
        ///AW EH
        ///AW EU
        ///AW EY
        ///AW F
        ///AW G
        ///AW H
        ///AW IH
        ///AW IY
        ///AW JH
        ///AW K
        ///AW L
        ///AW M
        ///AW N
        ///AW NG
        ///A [rest of string was truncated]&quot;;.
        /// </summary>
        public static string de_DE_wildcard12 {
            get {
                return ResourceManager.GetString("de_DE_wildcard12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A
        ///AW
        ///AX
        ///AY
        ///B
        ///D
        ///CH
        ///EH
        ///EU
        ///EY
        ///F
        ///G
        ///H
        ///IH
        ///IY
        ///JH
        ///K
        ///L
        ///M
        ///N
        ///NG
        ///OE
        ///OH
        ///OW
        ///OY
        ///P
        ///PF
        ///R
        ///S
        ///SH
        ///T
        ///TS
        ///UE
        ///UH
        ///UW
        ///UY
        ///V
        ///X
        ///Y
        ///Z
        ///ZH
        ///A A
        ///A AW
        ///A AX
        ///A AY
        ///A B
        ///A D
        ///A CH
        ///A EH
        ///A EU
        ///A EY
        ///A F
        ///A G
        ///A H
        ///A IH
        ///A IY
        ///A JH
        ///A K
        ///A L
        ///A M
        ///A N
        ///A NG
        ///A OE
        ///A OH
        ///A OW
        ///A OY
        ///A P
        ///A PF
        ///A R
        ///A S
        ///A SH
        ///A T
        ///A TS
        ///A UE
        ///A UH
        ///A UW
        ///A UY
        ///A V
        ///A X
        ///A Y
        ///A Z
        ///A ZH
        ///AW A
        ///AW AW
        ///AW AX
        ///AW AY
        ///AW B
        ///AW D
        ///AW CH
        ///AW EH
        ///AW EU
        ///AW EY
        ///AW F
        ///AW G
        ///AW H
        ///AW IH
        ///AW IY
        ///AW JH
        ///AW K
        ///AW L
        ///AW M
        ///AW N
        ///AW NG
        ///A [rest of string was truncated]&quot;;.
        /// </summary>
        public static string de_DE_wildcard123 {
            get {
                return ResourceManager.GetString("de_DE_wildcard123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AA
        ///AE
        ///AH
        ///AI
        ///AO
        ///AU
        ///AX
        ///E
        ///EH
        ///EI
        ///I
        ///IH
        ///O
        ///OI
        ///U
        ///UH
        ///B
        ///CH
        ///D
        ///DH
        ///F
        ///G
        ///H
        ///J
        ///JH
        ///K
        ///L
        ///M
        ///N
        ///NG
        ///P
        ///R
        ///S
        ///SH
        ///T
        ///TH
        ///V
        ///W
        ///Z
        ///ZH.
        /// </summary>
        public static string en_US_wildcard1 {
            get {
                return ResourceManager.GetString("en_US_wildcard1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AA
        ///AE
        ///AH
        ///AI
        ///AO
        ///AU
        ///AX
        ///E
        ///EH
        ///EI
        ///I
        ///IH
        ///O
        ///OI
        ///U
        ///UH
        ///B
        ///CH
        ///D
        ///DH
        ///F
        ///G
        ///H
        ///J
        ///JH
        ///K
        ///L
        ///M
        ///N
        ///NG
        ///P
        ///R
        ///S
        ///SH
        ///T
        ///TH
        ///V
        ///W
        ///Z
        ///ZH
        ///AA AA
        ///AA AE
        ///AA AH
        ///AA AI
        ///AA AO
        ///AA AU
        ///AA AX
        ///AA E
        ///AA EH
        ///AA EI
        ///AA I
        ///AA IH
        ///AA O
        ///AA OI
        ///AA U
        ///AA UH
        ///AA B
        ///AA CH
        ///AA D
        ///AA DH
        ///AA F
        ///AA G
        ///AA H
        ///AA J
        ///AA JH
        ///AA K
        ///AA L
        ///AA M
        ///AA N
        ///AA NG
        ///AA P
        ///AA R
        ///AA S
        ///AA SH
        ///AA T
        ///AA TH
        ///AA V
        ///AA W
        ///AA Z
        ///AA ZH
        ///AE AA
        ///AE AE
        ///AE AH
        ///AE AI
        ///AE AO
        ///AE AU
        ///AE AX
        ///AE E
        ///AE EH
        ///AE EI
        ///AE I
        ///AE IH
        ///AE O
        ///AE OI
        ///AE U
        ///AE UH
        ///AE B
        ///AE CH
        ///AE D
        ///AE DH
        ///AE F
        ///AE G
        ///AE H
        ///AE J
        ///AE JH
        ///AE K
        ///AE L
        ///AE M
        ///AE N
        ///AE NG
        ///AE P
        ///AE R
        ///AE S
        ///AE SH
        ///AE T
        ///AE [rest of string was truncated]&quot;;.
        /// </summary>
        public static string en_US_wildcard12 {
            get {
                return ResourceManager.GetString("en_US_wildcard12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AA
        ///AE
        ///AH
        ///AI
        ///AO
        ///AU
        ///AX
        ///E
        ///EH
        ///EI
        ///I
        ///IH
        ///O
        ///OI
        ///U
        ///UH
        ///B
        ///CH
        ///D
        ///DH
        ///F
        ///G
        ///H
        ///J
        ///JH
        ///K
        ///L
        ///M
        ///N
        ///NG
        ///P
        ///R
        ///S
        ///SH
        ///T
        ///TH
        ///V
        ///W
        ///Z
        ///ZH
        ///AA AA
        ///AA AE
        ///AA AH
        ///AA AI
        ///AA AO
        ///AA AU
        ///AA AX
        ///AA E
        ///AA EH
        ///AA EI
        ///AA I
        ///AA IH
        ///AA O
        ///AA OI
        ///AA U
        ///AA UH
        ///AA B
        ///AA CH
        ///AA D
        ///AA DH
        ///AA F
        ///AA G
        ///AA H
        ///AA J
        ///AA JH
        ///AA K
        ///AA L
        ///AA M
        ///AA N
        ///AA NG
        ///AA P
        ///AA R
        ///AA S
        ///AA SH
        ///AA T
        ///AA TH
        ///AA V
        ///AA W
        ///AA Z
        ///AA ZH
        ///AE AA
        ///AE AE
        ///AE AH
        ///AE AI
        ///AE AO
        ///AE AU
        ///AE AX
        ///AE E
        ///AE EH
        ///AE EI
        ///AE I
        ///AE IH
        ///AE O
        ///AE OI
        ///AE U
        ///AE UH
        ///AE B
        ///AE CH
        ///AE D
        ///AE DH
        ///AE F
        ///AE G
        ///AE H
        ///AE J
        ///AE JH
        ///AE K
        ///AE L
        ///AE M
        ///AE N
        ///AE NG
        ///AE P
        ///AE R
        ///AE S
        ///AE SH
        ///AE T
        ///AE [rest of string was truncated]&quot;;.
        /// </summary>
        public static string en_US_wildcard123 {
            get {
                return ResourceManager.GetString("en_US_wildcard123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A
        ///AN
        ///AO
        ///AX
        ///E
        ///EH
        ///EN
        ///EU
        ///I
        ///O
        ///OE
        ///OEN
        ///ON
        ///U
        ///Y
        ///B
        ///D
        ///F
        ///G
        ///J
        ///K
        ///L
        ///M
        ///N
        ///NG
        ///NJ
        ///P
        ///RH
        ///S
        ///SH
        ///T
        ///V
        ///W
        ///WJ
        ///Z
        ///ZH.
        /// </summary>
        public static string fr_FR_wildcard1 {
            get {
                return ResourceManager.GetString("fr_FR_wildcard1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A
        ///AN
        ///AO
        ///AX
        ///E
        ///EH
        ///EN
        ///EU
        ///I
        ///O
        ///OE
        ///OEN
        ///ON
        ///U
        ///Y
        ///B
        ///D
        ///F
        ///G
        ///J
        ///K
        ///L
        ///M
        ///N
        ///NG
        ///NJ
        ///P
        ///RH
        ///S
        ///SH
        ///T
        ///V
        ///W
        ///WJ
        ///Z
        ///ZH
        ///A A
        ///A AN
        ///A AO
        ///A AX
        ///A E
        ///A EH
        ///A EN
        ///A EU
        ///A I
        ///A O
        ///A OE
        ///A OEN
        ///A ON
        ///A U
        ///A Y
        ///A B
        ///A D
        ///A F
        ///A G
        ///A J
        ///A K
        ///A L
        ///A M
        ///A N
        ///A NG
        ///A NJ
        ///A P
        ///A RH
        ///A S
        ///A SH
        ///A T
        ///A V
        ///A W
        ///A WJ
        ///A Z
        ///A ZH
        ///AN A
        ///AN AN
        ///AN AO
        ///AN AX
        ///AN E
        ///AN EH
        ///AN EN
        ///AN EU
        ///AN I
        ///AN O
        ///AN OE
        ///AN OEN
        ///AN ON
        ///AN U
        ///AN Y
        ///AN B
        ///AN D
        ///AN F
        ///AN G
        ///AN J
        ///AN K
        ///AN L
        ///AN M
        ///AN N
        ///AN NG
        ///AN NJ
        ///AN P
        ///AN RH
        ///AN S
        ///AN SH
        ///AN T
        ///AN V
        ///AN W
        ///AN WJ
        ///AN Z
        ///AN ZH
        ///AO A
        ///AO AN
        ///AO AO
        ///AO AX
        ///AO E
        ///AO EH
        ///AO EN
        ///AO EU
        ///AO I
        ///AO O
        ///AO OE
        ///AO OEN [rest of string was truncated]&quot;;.
        /// </summary>
        public static string fr_FR_wildcard12 {
            get {
                return ResourceManager.GetString("fr_FR_wildcard12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A
        ///AN
        ///AO
        ///AX
        ///E
        ///EH
        ///EN
        ///EU
        ///I
        ///O
        ///OE
        ///OEN
        ///ON
        ///U
        ///Y
        ///B
        ///D
        ///F
        ///G
        ///J
        ///K
        ///L
        ///M
        ///N
        ///NG
        ///NJ
        ///P
        ///RH
        ///S
        ///SH
        ///T
        ///V
        ///W
        ///WJ
        ///Z
        ///ZH
        ///A A
        ///A AN
        ///A AO
        ///A AX
        ///A E
        ///A EH
        ///A EN
        ///A EU
        ///A I
        ///A O
        ///A OE
        ///A OEN
        ///A ON
        ///A U
        ///A Y
        ///A B
        ///A D
        ///A F
        ///A G
        ///A J
        ///A K
        ///A L
        ///A M
        ///A N
        ///A NG
        ///A NJ
        ///A P
        ///A RH
        ///A S
        ///A SH
        ///A T
        ///A V
        ///A W
        ///A WJ
        ///A Z
        ///A ZH
        ///AN A
        ///AN AN
        ///AN AO
        ///AN AX
        ///AN E
        ///AN EH
        ///AN EN
        ///AN EU
        ///AN I
        ///AN O
        ///AN OE
        ///AN OEN
        ///AN ON
        ///AN U
        ///AN Y
        ///AN B
        ///AN D
        ///AN F
        ///AN G
        ///AN J
        ///AN K
        ///AN L
        ///AN M
        ///AN N
        ///AN NG
        ///AN NJ
        ///AN P
        ///AN RH
        ///AN S
        ///AN SH
        ///AN T
        ///AN V
        ///AN W
        ///AN WJ
        ///AN Z
        ///AN ZH
        ///AO A
        ///AO AN
        ///AO AO
        ///AO AX
        ///AO E
        ///AO EH
        ///AO EN
        ///AO EU
        ///AO I
        ///AO O
        ///AO OE
        ///AO OEN [rest of string was truncated]&quot;;.
        /// </summary>
        public static string fr_FR_wildcard123 {
            get {
                return ResourceManager.GetString("fr_FR_wildcard123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///i
        ///i
        ///u
        ///u
        ///e
        ///e
        ///o
        ///o
        ///ga
        ///ki
        ///gi
        ///ku
        ///gu
        ///ke
        ///ge
        ///ko
        ///go
        ///sa
        ///za
        ///shi
        ///ji
        ///su
        ///zu
        ///se
        ///ze
        ///so
        ///zo
        ///ta
        ///da
        ///chi
        ///di
        ///q
        ///tsu
        ///du
        ///te
        ///de
        ///to
        ///do
        ///na
        ///ni
        ///nu
        ///ne
        ///no
        ///ha
        ///ba
        ///pa
        ///hi
        ///bi
        ///pi
        ///hu
        ///bu
        ///pu
        ///he
        ///be
        ///pe
        ///ho
        ///bo
        ///po
        ///ma
        ///mi
        ///mu
        ///me
        ///mo
        ///ya
        ///ya
        ///yu
        ///yu
        ///yo
        ///yo
        ///ra
        ///ri
        ///ru
        ///re
        ///ro
        ///wa
        ///wa
        ///wi
        ///we
        ///wo
        ///nn
        ///vu
        ///ke
        ///va
        ///vi
        ///ve
        ///vo
        ///.
        /// </summary>
        public static string ja_JP_wildcard1 {
            get {
                return ResourceManager.GetString("ja_JP_wildcard1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///i
        ///i
        ///u
        ///u
        ///e
        ///e
        ///o
        ///o
        ///ga
        ///ki
        ///gi
        ///ku
        ///gu
        ///ke
        ///ge
        ///ko
        ///go
        ///sa
        ///za
        ///shi
        ///ji
        ///su
        ///zu
        ///se
        ///ze
        ///so
        ///zo
        ///ta
        ///da
        ///chi
        ///di
        ///q
        ///tsu
        ///du
        ///te
        ///de
        ///to
        ///do
        ///na
        ///ni
        ///nu
        ///ne
        ///no
        ///ha
        ///ba
        ///pa
        ///hi
        ///bi
        ///pi
        ///hu
        ///bu
        ///pu
        ///he
        ///be
        ///pe
        ///ho
        ///bo
        ///po
        ///ma
        ///mi
        ///mu
        ///me
        ///mo
        ///ya
        ///ya
        ///yu
        ///yu
        ///yo
        ///yo
        ///ra
        ///ri
        ///ru
        ///re
        ///ro
        ///wa
        ///wa
        ///wi
        ///we
        ///wo
        ///nn
        ///vu
        ///ke
        ///va
        ///vi
        ///ve
        ///vo
        ///a a
        ///a i
        ///a i
        ///a u
        ///a u
        ///a e
        ///a e
        ///a o
        ///a o
        ///a ga
        ///a ki
        ///a gi
        ///a ku
        ///a gu
        ///a ke
        ///a ge
        ///a ko
        ///a go
        ///a sa
        ///a za
        ///a shi
        ///a ji
        ///a su
        ///a zu
        ///a se
        ///a ze
        ///a so
        ///a zo
        ///a ta
        ///a da        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ja_JP_wildcard12 {
            get {
                return ResourceManager.GetString("ja_JP_wildcard12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///i
        ///i
        ///u
        ///u
        ///e
        ///e
        ///o
        ///o
        ///ga
        ///ki
        ///gi
        ///ku
        ///gu
        ///ke
        ///ge
        ///ko
        ///go
        ///sa
        ///za
        ///shi
        ///ji
        ///su
        ///zu
        ///se
        ///ze
        ///so
        ///zo
        ///ta
        ///da
        ///chi
        ///di
        ///q
        ///tsu
        ///du
        ///te
        ///de
        ///to
        ///do
        ///na
        ///ni
        ///nu
        ///ne
        ///no
        ///ha
        ///ba
        ///pa
        ///hi
        ///bi
        ///pi
        ///hu
        ///bu
        ///pu
        ///he
        ///be
        ///pe
        ///ho
        ///bo
        ///po
        ///ma
        ///mi
        ///mu
        ///me
        ///mo
        ///ya
        ///ya
        ///yu
        ///yu
        ///yo
        ///yo
        ///ra
        ///ri
        ///ru
        ///re
        ///ro
        ///wa
        ///wa
        ///wi
        ///we
        ///wo
        ///nn
        ///vu
        ///ke
        ///va
        ///vi
        ///ve
        ///vo
        ///a a
        ///a i
        ///a i
        ///a u
        ///a u
        ///a e
        ///a e
        ///a o
        ///a o
        ///a ga
        ///a ki
        ///a gi
        ///a ku
        ///a gu
        ///a ke
        ///a ge
        ///a ko
        ///a go
        ///a sa
        ///a za
        ///a shi
        ///a ji
        ///a su
        ///a zu
        ///a se
        ///a ze
        ///a so
        ///a zo
        ///a ta
        ///a da        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ja_JP_wildcard123 {
            get {
                return ResourceManager.GetString("ja_JP_wildcard123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream sampleAudio {
            get {
                return ResourceManager.GetStream("sampleAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///ai
        ///an
        ///ang
        ///ao
        ///ba
        ///bai
        ///ban
        ///bang
        ///bao
        ///bei
        ///ben
        ///beng
        ///bi
        ///bian
        ///biao
        ///bie
        ///bin
        ///bing
        ///bo
        ///bu
        ///ca
        ///cai
        ///can
        ///cang
        ///cao
        ///ce
        ///cen
        ///ceng
        ///cha
        ///chai
        ///chan
        ///chang
        ///chao
        ///che
        ///chen
        ///cheng
        ///chi
        ///chong
        ///chou
        ///chu
        ///chuai
        ///chuan
        ///chuang
        ///chui
        ///chun
        ///chuo
        ///ci
        ///cong
        ///cou
        ///cu
        ///cuan
        ///cui
        ///cun
        ///cuo
        ///da
        ///dai
        ///dan
        ///dang
        ///dao
        ///de
        ///dei
        ///den
        ///deng
        ///di
        ///dia
        ///dian
        ///diao
        ///die
        ///ding
        ///diu
        ///dong
        ///dou
        ///du
        ///duan
        ///dui
        ///dun
        ///duo
        ///e
        ///ei
        ///en
        ///er
        ///fa
        ///fan
        ///fang
        ///fei
        ///fen
        ///feng
        ///fo
        ///fou
        ///fu
        ///ga
        ///gai
        ///gan
        ///gang
        ///gao
        ///ge
        ///gei
        ///gen
        ///geng [rest of string was truncated]&quot;;.
        /// </summary>
        public static string zh_CN_wildcard1 {
            get {
                return ResourceManager.GetString("zh_CN_wildcard1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///ai
        ///an
        ///ang
        ///ao
        ///ba
        ///bai
        ///ban
        ///bang
        ///bao
        ///bei
        ///ben
        ///beng
        ///bi
        ///bian
        ///biao
        ///bie
        ///bin
        ///bing
        ///bo
        ///bu
        ///ca
        ///cai
        ///can
        ///cang
        ///cao
        ///ce
        ///cen
        ///ceng
        ///cha
        ///chai
        ///chan
        ///chang
        ///chao
        ///che
        ///chen
        ///cheng
        ///chi
        ///chong
        ///chou
        ///chu
        ///chuai
        ///chuan
        ///chuang
        ///chui
        ///chun
        ///chuo
        ///ci
        ///cong
        ///cou
        ///cu
        ///cuan
        ///cui
        ///cun
        ///cuo
        ///da
        ///dai
        ///dan
        ///dang
        ///dao
        ///de
        ///dei
        ///den
        ///deng
        ///di
        ///dia
        ///dian
        ///diao
        ///die
        ///ding
        ///diu
        ///dong
        ///dou
        ///du
        ///duan
        ///dui
        ///dun
        ///duo
        ///e
        ///ei
        ///en
        ///er
        ///fa
        ///fan
        ///fang
        ///fei
        ///fen
        ///feng
        ///fo
        ///fou
        ///fu
        ///ga
        ///gai
        ///gan
        ///gang
        ///gao
        ///ge
        ///gei
        ///gen
        ///geng [rest of string was truncated]&quot;;.
        /// </summary>
        public static string zh_CN_wildcard12 {
            get {
                return ResourceManager.GetString("zh_CN_wildcard12", resourceCulture);
            }
        }
    }
}
